apiVersion: apps/v1
kind: Deployment
metadata:
  name: goviolin
  labels:
    app: goviolin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goviolin
  template:
    metadata:
      labels:
        app: goviolin
    spec:
      containers:
      - name: goviolin
        image: islam235/goviolin:4
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
